### ISSUE TITLE
mojee.io website down / taken

### ISSUE THREAD

**Issue by fabriciomurta** [MojeeIO/Mojee#2]
I used to keep mojee.io website open in my cellphone to use it as a emojy copypaste I used in some apps. Few days ago I noticed it didn't respond. Today it's loading something else. Maybe rename the website in the README.md to a github.io pages site?

**Comment by fabriciomurta** [comment]
Funny, just checked again and docs.mojee.io is loading from here. Yet `mojee.io` alone loads a strange site. Few days ago, Checking in my cellphone, I used to load mojee.io page from https://mojee.io/ and it landed on github. So perhaps that's a case of a domain takeover within github and some malicious user has abused it.

- Perhaps doing this would allow to get it back: [Verifying your custom domain for GitHub Pages](https://docs.github.com/en/enterprise-cloud@latest/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages)

**Comment by geoffreymcgill** [comment]
Confirmed, something strange is going on. The domain has not expired from our registrar account, so from the registration side, all is well. 

I will investigate. Thank you for pointing out this issue.

**Comment by fabriciomurta** [comment]
It was taken over by a malicious party, seems to be a common thing nowadays. If you follow the steps to verify and assign mojee.io to the mojeeio organization, it should become fixed.
There's nothing wrong with your registrar or your DNS entries. The malicious party just created a github pages with a `CNAME` file containing `mojee.io` and, as it was not taken elsewhere (this site uses docs.mojee.io), github accepted their binding.

**Comment by geoffreymcgill** [comment]
The mojee.io domain name is now verified, although there still appears to be an issue with GitHub accepting the value as a custom domain. The domain is still being flagged as "taken". 

I'm going to leave for another 24 hours and see if GitHub clears their system of the old non-verified projects, then try setting again. 

<img width="556" alt="Screenshot 2024-11-23 at 7 05 58 AM" src="https://github.com/user-attachments/assets/472f1017-e04c-4597-bbed-7f908202ab3b">

<img width="556" alt="Screenshot 2024-11-23 at 7 05 37 AM" src="https://github.com/user-attachments/assets/163cf494-1c87-49d1-b286-47b97833cad1">

**Comment by fabriciomurta** [comment]
https://mojee.io now loads the main page again. I guess it just needed some hours to settle.

**Comment by geoffreymcgill** [comment]
Turns out there are two domain verifications that need to be done at the project level. I completed the first verification for the domain and misunderstood that would then verify the domain for use in GitHub Pages. There is a second domain verification for using the domain in Pages.

All should be good now. Thanks again for pointing out this issue.
